title: "Zan Lab -- Computational Biology For Plant Genetics, Breeding and Ecology"
author: "Zan Lab"
description: "Zan Lab at xxx"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home }
  - {file: "Philosophy.md", title: Reserach}
  - {file: "Members.md", title: Members}
#  - {file: "Events.html", title: Events }
  - {file: "Publications.md", title: Publications}
  - {file: "Resources.md", title: Resources}
  - {file: "Outreach.md", title: Outreach}
  - {file: "Opportunities.md", title: Opportunities}
  - {file: "Contact.md", title: Contact}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yanjun_zan@aliyun.com"}
  - {title: Github, icon: github, url: "https://yanjunzan@github.io"}
  - {title: Bilibili, icon: rss, url: "https://space.bilibili.com/629646873"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
